numpy: Autospec creation for update from version 1.19.4 to version 1.19.5
Charles Harris (4):
      REL: prepare 1.19.x for further development
      BLD: use BUFFERSIZE=20 in OpenBLAS
      REL: Prepare for the NumPy 1.19.5 release.
      REL: NumPy 1.19.5 release.

Christoph Gohlke (1):
      Fix AttributeError: 'bool' object has no attribute 'ndim'

Matti Picus (1):
      BLD: update to OpenBLAS 0.3.13

Raghuveer Devulapalli (1):
      BUG: make a variable volatile to work around clang compiler bug (#18030)

Sebastian Berg (4):
      BUG: Fix segfault due to out of bound pointer in floatstatus check
      Update numpy/core/src/umath/simd.inc.src
      BUG: Fix subarray dtype used with too large count in fromfile
      BUG: Raise recursion and memory error during dimension discovery

Simon Graham (6):
      BUG: Fixed file handle leak in array_tofile.
      Update numpy/core/src/multiarray/methods.c
      BUG: array_tofile now always closes the original file handle.
      BUG: Made array_tofile exception safe.
      MAINT: Refactored array_tofile to use a helper function.
      TST: Check that tofile closes its Python handle when we pass it a str.

Veniamin Petrenko (1):
      BUG: fix np.timedelta64('nat').__format__ throwing an exception

bernie gray (1):
      BUG: ensure _UFuncNoLoopError can be pickled (#17377)